name: spk_diagnosa
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1
  intl: ^0.20.2
  collection: ^1.18.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/seeds/diseases.json
    - assets/seeds/symptoms.json
    - assets/seeds/rules.json

